export const metadata = {
  title: "Job Apply",
  description: "Generated by create next app",
};

import Navbar from "../(jobApply)/_navbar/Navbar";

export default function JobApplyLayout({ children }) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
