import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Job",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers> {children} </Providers>
      </body>
    </html>
  );
}
