export const metadata = {
  title: "Help & Support",
  description: "Generated by create next app",
};

export default function HelpSupportLayout({ children }) {
  return <section>{children}</section>
}